version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ./phpback/:/var/www/html/
    container_name: php
    environment:
      - DB_ROOT_PASSWORD=rootpassword
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./phpback/:/var/www/html/
    container_name: apache
  db:
    image: mariadb:${MARIADB_VERSION:-latest}
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    container_name: db
networks:
  frontend:
  backend: